/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 3;
=======
const int buildversion = 6;
>>>>>>> 6a6393295d2bce1156247412eb2ea207f5cd48e2
const char buildconfig[] = "ASST0";
